filter/table_x_low :  0.0
filter/table_x_high:  0.8
filter/table_y_low :  0.0
filter/table_y_high:  1.0
filter/table_z_low :  -0.01
filter/table_z_high:  0.3
filter/smoothing_radius: 0.04
filter/plane_seg_threshold: 0.0075
filter/plane_seg_max_iterations: 15
filter/col_seg_min_cluster_size: 100
filter/col_seg_max_cluster_size: 2000
filter/col_seg_dist_threshold: 0.020
filter/col_seg_min_saturation: 0.35
filter/col_seg_min_value: 0.3
filter/col_seg_scale_z: 0.87
filter/col_seg_scale_y: 0.92
filter/col_seg_center_y: 0.60
filter/col_seg_scale_x: 0.91
filter/col_seg_center_x: 0.29
filter/hue_red: 355
filter/hue_blue: 220
filter/hue_green: 85
filter/hue_yellow: 35
filter/hue_tol: 13
filter/block_plane_dist_threshold: 0.0022
filter/block_plane_max_iterations: 10
filter/block_plane_min_points: 30
filter/block_type_big_square: [0.037, 0.037, 0.073]
filter/block_type_big_slim: [0.020, 0.037, 0.073]
filter/block_type_cube: [0.037, 0.037, 0.035]
filter/block_type_small_square: [0.025, 0.025, 0.05]
filter/block_type_tol: 0.03

