filter/table_x_low :  0.44
filter/table_x_high:  1.24
filter/table_y_low : -0.5
filter/table_y_high:  0.5
filter/table_z_low : -0.225
filter/table_z_high: 0.1
filter/smoothing_radius: 0.025
filter/plane_seg_threshold: 0.012
filter/plane_seg_max_iterations: 10
filter/col_seg_min_cluster_size: 100
filter/col_seg_dist_threshold: 0.01
filter/col_seg_point_col_threshold: 60
filter/col_seg_region_col_threshold: 1
filter/outlier_remove_radius: 0.005
filter/outlier_remove_min_neighb: 10
filter/color_red: [220, 100, 100]
filter/color_blue: [100, 150, 210]
filter/color_green: [130, 200, 100]
filter/color_yellow: [250, 250, 40]
