filter/table_x_low :  0.44
filter/table_x_high:  1.24
filter/table_y_low : -0.5
filter/table_y_high:  0.5
filter/table_z_low : -0.225
filter/table_z_high: 0.1
filter/smoothing_radius: 0.025
filter/plane_seg_threshold: 0.010
filter/plane_seg_max_iterations: 10
filter/col_seg_min_cluster_size: 100
filter/col_seg_max_cluster_size: 2000
filter/col_seg_dist_threshold: 0.015
filter/hue_red: 355
filter/hue_blue: 220
filter/hue_green: 85
filter/hue_yellow: 35
filter/hue_tol: 15
filter/block_plane_dist_threshold: 0.003
filter/block_plane_max_iterations: 10
filter/block_plane_min_points: 30
filter/block_type_big_square: [0.05, 0.05, 0.091]
filter/block_type_big_slim: [0.028, 0.05, 0.091]
filter/block_type_cube: [0.05, 0.05, 0.05]
filter/block_type_small_square: [0.035, 0.035, 0.061]
filter/block_type_tol: 0.01

