#!/usr/bin/env python

# START - for debugging in visual studio code
# import ptvsd

# # 5678 is the default attach port in the VS Code debug configurations
# print("Waiting for debugger attach")
# ptvsd.enable_attach(address=('localhost', 5678), redirect_output=True)
# ptvsd.wait_for_attach()
# breakpoint()

# END - for debugging in visual studio code

import rospy

from reasoning_planning_helper.reasoning_planning_interface import *


def main():

    # init

    rospy.init_node('reasoning_planning_standalone_node', anonymous=True)

    rospy.Subscriber(
        '/rosplan_planner_interface/planner_output', String, plan_printer)


    get_scene_and_store_in_db()

    print_blocks_from_db()

    create_knowledge_from_scene_db()

    add_init_knowledge()    

    test_set_goal_for_stacked_test_scene()



    generate_problem()
    generate_plan()

    parse_plan()
    goal_reached = dispatch_plan()

    rospy.loginfo("Success of dispatching found plan? {}".format(goal_reached))

    rospy.loginfo("end of main reached!")


if __name__ == '__main__':
    main()
